spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rolesystem?useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    enabled: true
    cache: true  # 缓存
    check-template: true  # 检查模板是否存在
    check-template-location: true  # 检查模板位置是否存在
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

server:
  port: 80
  servlet:
    session:
      timeout: 300s

logging:
  file:
    path: ./log
  level:
    root: warn
    com.ilirus.rolesystem: info
    com.ilirus.rolesystem.dao: debug

mybatis:
  # config-location 和 configuration 不能同时使用
  # config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapping/*Mapper.xml
  type-aliases-package: com.ilirus.rolesystem.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

